import { Product } from "./types";

/**
 * Mock catalog shaped to mirror the WooCommerce REST/Store API product
 * schema (id, slug, sku, price, stock_status, categories, meta_data for
 * purity/mass/batch). Swap `getProducts` / `getProductBySlug` for real
 * fetches against the WooCommerce API once the WordPress site is live —
 * see lib/woocommerce.ts.
 */
export const products: Product[] = [
  {
    id: "2",
    slug: "bpc-157-10mg",
    sku: "BPC-10",
    name: "BPC-157 10MG",
    category: "peptides",
    categoryLabel: "Peptides",
    image: "/images/products/bpc-157.jpg",
    price: 70,
    bulkOption: { qty: 10, price: 560, savePercent: 20 },
    purity: "98.51%",
    avgMass: "11.22 mg",
    rating: 4.8,
    reviewCount: 89,
    inStock: true,
    shortDescription: "Higher-concentration BPC-157 for extended research protocols.",
    description:
      "BPC-157 10mg, lyophilized and independently verified for identity and purity. Supplied for laboratory research use only.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-BPC10-08", date: "2026-08-09", status: "PASS" },
  },
  {
    id: "7",
    slug: "retatrutide-10mg",
    sku: "RETA-10",
    name: "RETATRUTIDE 10MG",
    category: "peptides",
    categoryLabel: "Peptides",
    image: "/images/products/retatrutide.jpg",
    price: 90,
    bulkOption: { qty: 10, price: 720, savePercent: 20 },
    purity: "99.69%",
    avgMass: "10.99 mg",
    rating: 4.7,
    reviewCount: 45,
    inStock: true,
    shortDescription: "Tri-agonist research peptide, standard concentration.",
    description:
      "Retatrutide 10mg vial for research protocols. 99.69% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-RETA10-07", date: "2026-07-30", status: "PASS" },
  },
  {
    id: "10",
    slug: "tesamorelin-10mg",
    sku: "TESA-10",
    name: "TESAMORELIN 10MG",
    category: "peptides",
    categoryLabel: "Peptides",
    image: "/images/products/tesamorelin.jpg",
    price: 90,
    bulkOption: { qty: 10, price: 720, savePercent: 20 },
    purity: "99.86%",
    avgMass: "11.83 mg",
    rating: 4.6,
    reviewCount: 29,
    inStock: true,
    shortDescription: "GHRH-analog research peptide, standard concentration.",
    description:
      "Tesamorelin 10mg vial for research protocols. 99.86% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-TESA10-07", date: "2026-07-18", status: "PASS" },
  },
  {
    id: "17",
    slug: "ghk-cu-50mg",
    sku: "GHK-50",
    name: "GHK-CU 50MG",
    category: "ancillaries",
    categoryLabel: "Peptides, Ancillaries",
    image: "/images/products/ghk-cu.jpg",
    price: 65,
    bulkOption: { qty: 10, price: 520, savePercent: 20 },
    purity: "99.4%",
    avgMass: "50.1 mg",
    rating: 4.7,
    reviewCount: 24,
    inStock: true,
    shortDescription: "Copper-peptide research compound, standard concentration.",
    description: "GHK-Cu 50mg vial for research protocols. 99.4% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-GHK50-08", date: "2026-08-16", status: "PASS" },
  },
  {
    id: "18",
    slug: "mots-c-10mg",
    sku: "MOTS-10",
    name: "MOTS-C 10MG",
    category: "ancillaries",
    categoryLabel: "Peptides, Ancillaries",
    image: "/images/products/mots-c.jpg",
    price: 75,
    bulkOption: { qty: 10, price: 600, savePercent: 20 },
    purity: "99.5%",
    avgMass: "10.15 mg",
    rating: 4.8,
    reviewCount: 17,
    inStock: true,
    shortDescription: "Mitochondrial-derived peptide, standard concentration.",
    description: "MOTS-c 10mg vial for research protocols. 99.5% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-MOTS10-08", date: "2026-08-17", status: "PASS" },
  },
  {
    id: "19",
    slug: "5-amino-1mq-50mg",
    sku: "5AM1MQ-50",
    name: "5-AMINO-1MQ 50MG",
    category: "ancillaries",
    categoryLabel: "Peptides, Ancillaries",
    image: "/images/products/5-amino-1mq.jpg",
    price: 70,
    bulkOption: { qty: 10, price: 560, savePercent: 20 },
    purity: "99.3%",
    avgMass: "50.2 mg",
    rating: 4.6,
    reviewCount: 14,
    inStock: true,
    shortDescription: "NNMT-inhibitor research compound, standard concentration.",
    description: "5-Amino-1MQ 50mg vial for research protocols. 99.3% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-5AM1MQ-08", date: "2026-08-18", status: "PASS" },
  },
  {
    id: "20",
    slug: "hgh-24iu",
    sku: "HGH-24",
    name: "HGH 24IU",
    category: "growth-hormone",
    categoryLabel: "Growth Hormone",
    image: "/images/products/hgh.jpg",
    price: 220,
    purity: "97.1%",
    avgMass: "24.3 ius",
    rating: 4.8,
    reviewCount: 33,
    inStock: true,
    shortDescription: "Growth hormone research vial, standard concentration.",
    description: "Growth hormone 24IU vial for research protocols. 97.1% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    batch: { code: "ALT-HGH24-08", date: "2026-08-19", status: "PASS" },
  },
  {
    id: "21",
    slug: "thymosin-alpha-1-5mg",
    sku: "TA1-5",
    name: "THYMOSIN ALPHA-1 5MG",
    category: "peptides",
    categoryLabel: "Peptides",
    image: "/images/products/thymosin-alpha-1.jpg",
    price: 60,
    bulkOption: { qty: 10, price: 480, savePercent: 20 },
    purity: "99.5%",
    avgMass: "5.06 mg",
    rating: 4.7,
    reviewCount: 21,
    inStock: true,
    shortDescription: "Immune-modulating research peptide, standard concentration.",
    description: "Thymosin Alpha-1 5mg vial for research protocols. 99.5% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-TA15-08", date: "2026-08-19", status: "PASS" },
  },
  {
    id: "22",
    slug: "wolverine-stack-20mg",
    sku: "WOLV-20",
    name: "WOLVERINE STACK 20MG",
    category: "peptides",
    categoryLabel: "Peptides",
    image: "/images/products/wolverine-stack.jpg",
    price: 95,
    bulkOption: { qty: 10, price: 760, savePercent: 20 },
    avgMass: "20.4 mg",
    rating: 4.8,
    reviewCount: 26,
    inStock: true,
    shortDescription: "Pre-combined recovery blend for research convenience.",
    description: "Wolverine Stack 20mg blend for research protocols, independently tested for identity and mass.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-WOLV20-08", date: "2026-08-20", status: "PASS" },
  },
  {
    id: "23",
    slug: "glow-70mg",
    sku: "GLOW-70",
    name: "GLOW 70MG",
    category: "peptides",
    categoryLabel: "Peptides",
    image: "/images/products/glow.jpg",
    price: 110,
    bulkOption: { qty: 10, price: 880, savePercent: 20 },
    avgMass: "70.3 mg",
    rating: 4.7,
    reviewCount: 19,
    inStock: true,
    shortDescription: "Pre-combined cellular-support blend for research convenience.",
    description: "GLOW 70mg blend for research protocols, independently tested for identity and mass.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-GLOW70-08", date: "2026-08-20", status: "PASS" },
  },
  {
    id: "24",
    slug: "sermorelin-10mg",
    sku: "SERM-10",
    name: "SERMORELIN 10MG",
    category: "peptides",
    categoryLabel: "Peptides",
    image: "/images/products/sermorelin.jpg",
    price: 65,
    bulkOption: { qty: 10, price: 520, savePercent: 20 },
    purity: "99.4%",
    avgMass: "10.11 mg",
    rating: 4.6,
    reviewCount: 12,
    inStock: true,
    shortDescription: "GHRH-analog research peptide, standard concentration.",
    description: "Sermorelin 10mg vial for research protocols. 99.4% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-SERM10-08", date: "2026-08-21", status: "PASS" },
  },
  {
    id: "25",
    slug: "klow-80mg",
    sku: "KLOW-80",
    name: "KLOW 80MG",
    category: "peptides",
    categoryLabel: "Peptides",
    image: "/images/products/klow.jpg",
    price: 125,
    bulkOption: { qty: 10, price: 1000, savePercent: 20 },
    avgMass: "80.2 mg",
    rating: 4.8,
    reviewCount: 15,
    inStock: true,
    shortDescription: "Pre-combined cellular-support blend for research convenience.",
    description: "KLOW 80mg blend for research protocols, independently tested for identity and mass.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-KLOW80-08", date: "2026-08-21", status: "PASS" },
  },
  {
    id: "26",
    slug: "selank-10mg",
    sku: "SEL-10",
    name: "SELANK 10MG",
    category: "peptides",
    categoryLabel: "Peptides",
    image: "/images/products/selank.jpg",
    price: 60,
    bulkOption: { qty: 10, price: 480, savePercent: 20 },
    purity: "99.4%",
    avgMass: "10.08 mg",
    rating: 4.7,
    reviewCount: 18,
    inStock: true,
    shortDescription: "Anxiolytic peptide research compound, standard concentration.",
    description: "Selank 10mg vial for research protocols. 99.4% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-SEL10-08", date: "2026-08-22", status: "PASS" },
  },
  {
    id: "27",
    slug: "cjc-1295-no-dac-5mg",
    sku: "CJC-5",
    name: "CJC-1295 WITHOUT DAC 5MG",
    category: "peptides",
    categoryLabel: "Peptides",
    image: "/images/products/cjc-1295.jpg",
    price: 70,
    bulkOption: { qty: 10, price: 560, savePercent: 20 },
    purity: "99.6%",
    avgMass: "5.03 mg",
    rating: 4.8,
    reviewCount: 23,
    inStock: true,
    shortDescription: "GHRH-analog research peptide, standard concentration.",
    description: "CJC-1295 without DAC 5mg vial for research protocols. 99.6% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-CJC5-08", date: "2026-08-22", status: "PASS" },
  },
  {
    id: "28",
    slug: "ace-031-1mg",
    sku: "ACE031-1",
    name: "ACE-031 1MG",
    category: "peptides",
    categoryLabel: "Peptides",
    image: "/images/products/ace-031.png",
    price: 110,
    bulkOption: { qty: 10, price: 880, savePercent: 20 },
    purity: "98.9%",
    avgMass: "1.04 mg",
    rating: 4.6,
    reviewCount: 9,
    inStock: true,
    shortDescription: "Myostatin-pathway research protein, standard concentration.",
    description: "ACE-031 1mg vial for research protocols. 98.9% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-ACE031-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "29",
    slug: "adipotide-5mg",
    sku: "ADIPO-5",
    name: "ADIPOTIDE 5MG",
    category: "peptides",
    categoryLabel: "Peptides",
    image: "/images/products/adipotide.png",
    price: 85,
    bulkOption: { qty: 10, price: 680, savePercent: 20 },
    purity: "99.1%",
    avgMass: "5.05 mg",
    rating: 4.6,
    reviewCount: 11,
    inStock: true,
    shortDescription: "Vascular-targeted research peptide, standard concentration.",
    description: "Adipotide 5mg vial for research protocols. 99.1% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-ADIPO5-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "30",
    slug: "ahk-cu-100mg",
    sku: "AHK-100",
    name: "AHK-CU 100MG",
    category: "ancillaries",
    categoryLabel: "Peptides, Ancillaries",
    image: "/images/products/ahk-cu.png",
    price: 70,
    bulkOption: { qty: 10, price: 560, savePercent: 20 },
    purity: "99.2%",
    avgMass: "100.4 mg",
    rating: 4.7,
    reviewCount: 13,
    inStock: true,
    shortDescription: "Copper-peptide research compound, standard concentration.",
    description: "AHK-Cu 100mg vial for research protocols. 99.2% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-AHK100-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "31",
    slug: "aicar-50mg",
    sku: "AICAR-50",
    name: "AICAR 50MG",
    category: "peptides",
    categoryLabel: "Peptides",
    image: "/images/products/aicar.png",
    price: 80,
    bulkOption: { qty: 10, price: 640, savePercent: 20 },
    purity: "99.0%",
    avgMass: "50.3 mg",
    rating: 4.6,
    reviewCount: 10,
    inStock: true,
    shortDescription: "AMPK-activating research compound, standard concentration.",
    description: "AICAR 50mg vial for research protocols. 99.0% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-AICAR50-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "32",
    slug: "alprostadil-20mg",
    sku: "ALPRO-20",
    name: "ALPROSTADIL 20MG",
    category: "peptides",
    categoryLabel: "Peptides",
    image: "/images/products/alprostadil.png",
    price: 60,
    bulkOption: { qty: 10, price: 480, savePercent: 20 },
    purity: "99.3%",
    avgMass: "20.2 mg",
    rating: 4.5,
    reviewCount: 8,
    inStock: true,
    shortDescription: "Prostaglandin E1 research compound, standard concentration.",
    description: "Alprostadil 20mg vial for research protocols. 99.3% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-ALPRO20-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "33",
    slug: "aod-9604-5mg",
    sku: "AOD-5",
    name: "AOD-9604 5MG",
    category: "peptides",
    categoryLabel: "Peptides",
    image: "/images/products/aod-9604.png",
    price: 70,
    bulkOption: { qty: 10, price: 560, savePercent: 20 },
    purity: "99.4%",
    avgMass: "5.07 mg",
    rating: 4.7,
    reviewCount: 16,
    inStock: true,
    shortDescription: "Modified hGH-fragment research peptide, standard concentration.",
    description: "AOD-9604 5mg vial for research protocols. 99.4% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-AOD5-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "34",
    slug: "ara-290-10mg",
    sku: "ARA290-10",
    name: "ARA-290 10MG",
    category: "peptides",
    categoryLabel: "Peptides",
    image: "/images/products/ara-290.png",
    price: 75,
    bulkOption: { qty: 10, price: 600, savePercent: 20 },
    purity: "99.1%",
    avgMass: "10.09 mg",
    rating: 4.6,
    reviewCount: 10,
    inStock: true,
    shortDescription: "Erythropoietin-derived research peptide, standard concentration.",
    description: "ARA-290 10mg vial for research protocols. 99.1% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-ARA290-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "35",
    slug: "bacteriostatic-water-10ml",
    sku: "BACW-10",
    name: "BACTERIOSTATIC WATER 10ML",
    category: "ancillaries",
    categoryLabel: "Ancillaries",
    image: "/images/products/bacteriostatic-water.png",
    price: 15,
    rating: 4.9,
    reviewCount: 41,
    inStock: true,
    shortDescription: "Sterile diluent for laboratory reconstitution use.",
    description: "10ml bacteriostatic water for laboratory reconstitution use only. Not for human use.",
    storage: "Store at room temperature, away from direct light. Discard if solution becomes cloudy.",
    batch: { code: "ALT-BACW10-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "36",
    slug: "cagrilintide-5mg",
    sku: "CAGRI-5",
    name: "CAGRILINTIDE 5MG",
    category: "peptides",
    categoryLabel: "Peptides",
    image: "/images/products/cagrilintide.png",
    price: 90,
    bulkOption: { qty: 10, price: 720, savePercent: 20 },
    purity: "99.5%",
    avgMass: "5.02 mg",
    rating: 4.7,
    reviewCount: 22,
    inStock: true,
    shortDescription: "Amylin-analog research peptide, standard concentration.",
    description: "Cagrilintide 5mg vial for research protocols. 99.5% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-CAGRI5-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "37",
    slug: "cjc-1295-with-dac-5mg",
    sku: "CJCDAC-5",
    name: "CJC-1295 WITH DAC 5MG",
    category: "growth-hormone",
    categoryLabel: "Growth Hormone",
    image: "/images/products/cjc-1295-with-dac.png",
    price: 75,
    bulkOption: { qty: 10, price: 600, savePercent: 20 },
    purity: "99.3%",
    avgMass: "5.04 mg",
    rating: 4.7,
    reviewCount: 19,
    inStock: true,
    shortDescription: "Long-acting GHRH-analog research peptide, standard concentration.",
    description: "CJC-1295 with DAC 5mg vial for research protocols. 99.3% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-CJCDAC5-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "38",
    slug: "cjc-1295-without-dac-ipamorelin-10mg",
    sku: "CJCIPA-10",
    name: "CJC-1295 WITHOUT DAC + IPAMORELIN 10MG",
    category: "growth-hormone",
    categoryLabel: "Growth Hormone",
    image: "/images/products/cjc-1295-without-dac-ipamorelin.png",
    price: 85,
    bulkOption: { qty: 10, price: 680, savePercent: 20 },
    avgMass: "10.11 mg",
    rating: 4.8,
    reviewCount: 27,
    inStock: true,
    shortDescription: "Pre-combined GHRH/GHRP research blend for research convenience.",
    description: "CJC-1295 without DAC + Ipamorelin 10mg blend for research protocols, independently tested for identity and mass.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-CJCIPA10-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "39",
    slug: "dihexa-10mg",
    sku: "DIHEXA-10",
    name: "DIHEXA 10MG",
    category: "peptides",
    categoryLabel: "Peptides",
    image: "/images/products/dihexa.png",
    price: 95,
    bulkOption: { qty: 10, price: 760, savePercent: 20 },
    purity: "99.0%",
    avgMass: "10.06 mg",
    rating: 4.6,
    reviewCount: 12,
    inStock: true,
    shortDescription: "Angiotensin IV-derived research compound, standard concentration.",
    description: "Dihexa 10mg vial for research protocols. 99.0% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-DIHEXA10-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "40",
    slug: "dsip-5mg",
    sku: "DSIP-5",
    name: "DSIP 5MG",
    category: "peptides",
    categoryLabel: "Peptides",
    image: "/images/products/dsip.png",
    price: 55,
    bulkOption: { qty: 10, price: 440, savePercent: 20 },
    purity: "99.2%",
    avgMass: "5.03 mg",
    rating: 4.6,
    reviewCount: 15,
    inStock: true,
    shortDescription: "Delta sleep-inducing research peptide, standard concentration.",
    description: "DSIP 5mg vial for research protocols. 99.2% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-DSIP5-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "41",
    slug: "epithalon-10mg",
    sku: "EPI-10",
    name: "EPITHALON 10MG",
    category: "peptides",
    categoryLabel: "Peptides",
    image: "/images/products/epithalon.png",
    price: 70,
    bulkOption: { qty: 10, price: 560, savePercent: 20 },
    purity: "99.6%",
    avgMass: "10.03 mg",
    rating: 4.8,
    reviewCount: 24,
    inStock: true,
    shortDescription: "Telomerase-activating tetrapeptide research compound, standard concentration.",
    description: "Epithalon 10mg vial for research protocols. 99.6% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-EPI10-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "42",
    slug: "follistatin-344-1mg",
    sku: "FOL344-1",
    name: "FOLLISTATIN-344 1MG",
    category: "peptides",
    categoryLabel: "Peptides",
    image: "/images/products/follistatin-344.png",
    price: 140,
    bulkOption: { qty: 10, price: 1120, savePercent: 20 },
    purity: "98.8%",
    avgMass: "1.02 mg",
    rating: 4.7,
    reviewCount: 14,
    inStock: true,
    shortDescription: "Myostatin-binding research protein, standard concentration.",
    description: "Follistatin-344 1mg vial for research protocols. 98.8% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-FOL3441-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "43",
    slug: "foxo4-dri-10mg",
    sku: "FOXO4-10",
    name: "FOXO4-DRI 10MG",
    category: "peptides",
    categoryLabel: "Peptides",
    image: "/images/products/foxo4-dri.png",
    price: 100,
    bulkOption: { qty: 10, price: 800, savePercent: 20 },
    purity: "98.9%",
    avgMass: "10.08 mg",
    rating: 4.6,
    reviewCount: 9,
    inStock: true,
    shortDescription: "Senescent-cell-targeting research peptide, standard concentration.",
    description: "FOXO4-DRI 10mg vial for research protocols. 98.9% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-FOXO410-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "44",
    slug: "gdf-8-1mg",
    sku: "GDF8-1",
    name: "GDF-8 1MG",
    category: "peptides",
    categoryLabel: "Peptides",
    image: "/images/products/gdf-8.png",
    price: 120,
    bulkOption: { qty: 10, price: 960, savePercent: 20 },
    purity: "98.7%",
    avgMass: "1.03 mg",
    rating: 4.5,
    reviewCount: 7,
    inStock: true,
    shortDescription: "Growth differentiation factor research protein, standard concentration.",
    description: "GDF-8 1mg vial for research protocols. 98.7% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-GDF81-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "45",
    slug: "ghrp-2-5mg",
    sku: "GHRP2-5",
    name: "GHRP-2 5MG",
    category: "growth-hormone",
    categoryLabel: "Growth Hormone",
    image: "/images/products/ghrp-2.png",
    price: 50,
    bulkOption: { qty: 10, price: 400, savePercent: 20 },
    purity: "99.4%",
    avgMass: "5.05 mg",
    rating: 4.7,
    reviewCount: 20,
    inStock: true,
    shortDescription: "Growth hormone releasing research peptide, standard concentration.",
    description: "GHRP-2 5mg vial for research protocols. 99.4% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-GHRP25-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "46",
    slug: "ghrp-6-5mg",
    sku: "GHRP6-5",
    name: "GHRP-6 5MG",
    category: "growth-hormone",
    categoryLabel: "Growth Hormone",
    image: "/images/products/ghrp-6.png",
    price: 50,
    bulkOption: { qty: 10, price: 400, savePercent: 20 },
    purity: "99.3%",
    avgMass: "5.06 mg",
    rating: 4.6,
    reviewCount: 17,
    inStock: true,
    shortDescription: "Growth hormone releasing research peptide, standard concentration.",
    description: "GHRP-6 5mg vial for research protocols. 99.3% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-GHRP65-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "47",
    slug: "glutathione-1500mg",
    sku: "GLUT-1500",
    name: "GLUTATHIONE 1500MG",
    category: "ancillaries",
    categoryLabel: "Ancillaries",
    image: "/images/products/glutathione.png",
    price: 75,
    bulkOption: { qty: 10, price: 600, savePercent: 20 },
    purity: "99.1%",
    avgMass: "1512 mg",
    rating: 4.7,
    reviewCount: 18,
    inStock: true,
    shortDescription: "Antioxidant tripeptide research compound, standard concentration.",
    description: "Glutathione 1500mg vial for research protocols. 99.1% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-GLUT1500-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "48",
    slug: "gonadorelin-5mg",
    sku: "GONAD-5",
    name: "GONADORELIN 5MG",
    category: "peptides",
    categoryLabel: "Peptides",
    image: "/images/products/gonadorelin.png",
    price: 60,
    bulkOption: { qty: 10, price: 480, savePercent: 20 },
    purity: "99.3%",
    avgMass: "5.02 mg",
    rating: 4.6,
    reviewCount: 13,
    inStock: true,
    shortDescription: "GnRH-analog research peptide, standard concentration.",
    description: "Gonadorelin 5mg vial for research protocols. 99.3% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-GONAD5-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "49",
    slug: "hexarelin-5mg",
    sku: "HEXA-5",
    name: "HEXARELIN 5MG",
    category: "growth-hormone",
    categoryLabel: "Growth Hormone",
    image: "/images/products/hexarelin.png",
    price: 55,
    bulkOption: { qty: 10, price: 440, savePercent: 20 },
    purity: "99.4%",
    avgMass: "5.04 mg",
    rating: 4.7,
    reviewCount: 15,
    inStock: true,
    shortDescription: "Potent growth hormone releasing research peptide, standard concentration.",
    description: "Hexarelin 5mg vial for research protocols. 99.4% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-HEXA5-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "50",
    slug: "igf-1-des-2mg",
    sku: "IGFDES-2",
    name: "IGF-1 DES 2MG",
    category: "growth-hormone",
    categoryLabel: "Growth Hormone",
    image: "/images/products/igf-1-des.png",
    price: 110,
    bulkOption: { qty: 10, price: 880, savePercent: 20 },
    purity: "98.6%",
    avgMass: "2.04 mg",
    rating: 4.6,
    reviewCount: 10,
    inStock: true,
    shortDescription: "Des(1-3) IGF-1 variant research protein, standard concentration.",
    description: "IGF-1 DES 2mg vial for research protocols. 98.6% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-IGFDES2-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "51",
    slug: "igf-1-lr3-1mg",
    sku: "IGFLR3-1",
    name: "IGF-1 LR3 1MG",
    category: "growth-hormone",
    categoryLabel: "Growth Hormone",
    image: "/images/products/igf-1-lr3.png",
    price: 90,
    bulkOption: { qty: 10, price: 720, savePercent: 20 },
    purity: "98.8%",
    avgMass: "1.05 mg",
    rating: 4.7,
    reviewCount: 21,
    inStock: true,
    shortDescription: "Long R3 IGF-1 variant research protein, standard concentration.",
    description: "IGF-1 LR3 1mg vial for research protocols. 98.8% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-IGFLR31-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "52",
    slug: "ipamorelin-5mg",
    sku: "IPAM-5",
    name: "IPAMORELIN 5MG",
    category: "growth-hormone",
    categoryLabel: "Growth Hormone",
    image: "/images/products/ipamorelin.png",
    price: 55,
    bulkOption: { qty: 10, price: 440, savePercent: 20 },
    purity: "99.5%",
    avgMass: "5.03 mg",
    rating: 4.8,
    reviewCount: 30,
    inStock: true,
    shortDescription: "Selective growth hormone secretagogue research peptide, standard concentration.",
    description: "Ipamorelin 5mg vial for research protocols. 99.5% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-IPAM5-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "53",
    slug: "kisspeptin-10-5mg",
    sku: "KISS10-5",
    name: "KISSPEPTIN-10 5MG",
    category: "peptides",
    categoryLabel: "Peptides",
    image: "/images/products/kisspeptin-10.png",
    price: 65,
    bulkOption: { qty: 10, price: 520, savePercent: 20 },
    purity: "99.2%",
    avgMass: "5.04 mg",
    rating: 4.6,
    reviewCount: 12,
    inStock: true,
    shortDescription: "Kisspeptin research peptide, standard concentration.",
    description: "Kisspeptin-10 5mg vial for research protocols. 99.2% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-KISS105-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "54",
    slug: "kpv-10mg",
    sku: "KPV-10",
    name: "KPV 10MG",
    category: "peptides",
    categoryLabel: "Peptides",
    image: "/images/products/kpv.png",
    price: 65,
    bulkOption: { qty: 10, price: 520, savePercent: 20 },
    purity: "99.5%",
    avgMass: "10.02 mg",
    rating: 4.7,
    reviewCount: 16,
    inStock: true,
    shortDescription: "Anti-inflammatory tripeptide research compound, standard concentration.",
    description: "KPV 10mg vial for research protocols. 99.5% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-KPV10-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "55",
    slug: "ll-37-5mg",
    sku: "LL37-5",
    name: "LL-37 5MG",
    category: "peptides",
    categoryLabel: "Peptides",
    image: "/images/products/ll-37.png",
    price: 70,
    bulkOption: { qty: 10, price: 560, savePercent: 20 },
    purity: "99.0%",
    avgMass: "5.06 mg",
    rating: 4.6,
    reviewCount: 11,
    inStock: true,
    shortDescription: "Antimicrobial peptide research compound, standard concentration.",
    description: "LL-37 5mg vial for research protocols. 99.0% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-LL375-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "56",
    slug: "mazdutide-5mg",
    sku: "MAZD-5",
    name: "MAZDUTIDE 5MG",
    category: "peptides",
    categoryLabel: "Peptides",
    image: "/images/products/mazdutide.png",
    price: 95,
    bulkOption: { qty: 10, price: 760, savePercent: 20 },
    purity: "99.6%",
    avgMass: "5.03 mg",
    rating: 4.7,
    reviewCount: 19,
    inStock: true,
    shortDescription: "GLP-1/glucagon dual-agonist research peptide, standard concentration.",
    description: "Mazdutide 5mg vial for research protocols. 99.6% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-MAZD5-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "57",
    slug: "mgf-2mg",
    sku: "MGF-2",
    name: "MGF 2MG",
    category: "growth-hormone",
    categoryLabel: "Growth Hormone",
    image: "/images/products/mgf.png",
    price: 65,
    bulkOption: { qty: 10, price: 520, savePercent: 20 },
    purity: "99.1%",
    avgMass: "2.02 mg",
    rating: 4.6,
    reviewCount: 14,
    inStock: true,
    shortDescription: "Mechano growth factor research peptide, standard concentration.",
    description: "MGF 2mg vial for research protocols. 99.1% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-MGF2-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "58",
    slug: "mt-1-10mg",
    sku: "MT1-10",
    name: "MT-1 10MG",
    category: "peptides",
    categoryLabel: "Peptides",
    image: "/images/products/mt-1.png",
    price: 70,
    bulkOption: { qty: 10, price: 560, savePercent: 20 },
    purity: "99.3%",
    avgMass: "10.04 mg",
    rating: 4.6,
    reviewCount: 13,
    inStock: true,
    shortDescription: "Melanocortin research peptide, standard concentration.",
    description: "MT-1 10mg vial for research protocols. 99.3% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-MT110-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "59",
    slug: "mt-2-10mg",
    sku: "MT2-10",
    name: "MT-2 10MG",
    category: "peptides",
    categoryLabel: "Peptides",
    image: "/images/products/mt-2.png",
    price: 60,
    bulkOption: { qty: 10, price: 480, savePercent: 20 },
    purity: "99.4%",
    avgMass: "10.03 mg",
    rating: 4.8,
    reviewCount: 28,
    inStock: true,
    shortDescription: "Melanocortin research peptide, standard concentration.",
    description: "MT-2 10mg vial for research protocols. 99.4% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-MT210-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "60",
    slug: "nad-plus-500mg",
    sku: "NAD-500",
    name: "NAD+ 500MG",
    category: "ancillaries",
    categoryLabel: "Ancillaries",
    image: "/images/products/nad-plus.png",
    price: 110,
    bulkOption: { qty: 10, price: 880, savePercent: 20 },
    purity: "99.0%",
    avgMass: "504 mg",
    rating: 4.8,
    reviewCount: 25,
    inStock: true,
    shortDescription: "Nicotinamide adenine dinucleotide research compound, standard concentration.",
    description: "NAD+ 500mg vial for research protocols. 99.0% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-NAD500-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "61",
    slug: "oxytocin-5mg",
    sku: "OXY-5",
    name: "OXYTOCIN 5MG",
    category: "peptides",
    categoryLabel: "Peptides",
    image: "/images/products/oxytocin.png",
    price: 50,
    bulkOption: { qty: 10, price: 400, savePercent: 20 },
    purity: "99.4%",
    avgMass: "5.02 mg",
    rating: 4.6,
    reviewCount: 12,
    inStock: true,
    shortDescription: "Neuropeptide hormone research compound, standard concentration.",
    description: "Oxytocin 5mg vial for research protocols. 99.4% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-OXY5-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "62",
    slug: "peg-mgf-2mg",
    sku: "PEGMGF-2",
    name: "PEG-MGF 2MG",
    category: "growth-hormone",
    categoryLabel: "Growth Hormone",
    image: "/images/products/peg-mgf.png",
    price: 70,
    bulkOption: { qty: 10, price: 560, savePercent: 20 },
    purity: "99.0%",
    avgMass: "2.03 mg",
    rating: 4.6,
    reviewCount: 10,
    inStock: true,
    shortDescription: "Pegylated mechano growth factor research peptide, standard concentration.",
    description: "PEG-MGF 2mg vial for research protocols. 99.0% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-PEGMGF2-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "63",
    slug: "pinealon-10mg",
    sku: "PINEAL-10",
    name: "PINEALON 10MG",
    category: "peptides",
    categoryLabel: "Peptides",
    image: "/images/products/pinealon.png",
    price: 60,
    bulkOption: { qty: 10, price: 480, savePercent: 20 },
    purity: "99.3%",
    avgMass: "10.05 mg",
    rating: 4.6,
    reviewCount: 9,
    inStock: true,
    shortDescription: "Neuroprotective tripeptide research compound, standard concentration.",
    description: "Pinealon 10mg vial for research protocols. 99.3% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-PINEAL10-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "64",
    slug: "pt-141-10mg",
    sku: "PT141-10",
    name: "PT-141 10MG",
    category: "peptides",
    categoryLabel: "Peptides",
    image: "/images/products/pt-141.png",
    price: 65,
    bulkOption: { qty: 10, price: 520, savePercent: 20 },
    purity: "99.5%",
    avgMass: "10.02 mg",
    rating: 4.8,
    reviewCount: 33,
    inStock: true,
    shortDescription: "Melanocortin research peptide, standard concentration.",
    description: "PT-141 10mg vial for research protocols. 99.5% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-PT14110-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "65",
    slug: "rejuv-70mg",
    sku: "REJUV-70",
    name: "REJUV 70MG",
    category: "peptides",
    categoryLabel: "Peptides",
    image: "/images/products/rejuv.png",
    price: 115,
    bulkOption: { qty: 10, price: 920, savePercent: 20 },
    avgMass: "70.2 mg",
    rating: 4.7,
    reviewCount: 16,
    inStock: true,
    shortDescription: "Pre-combined cellular-support blend for research convenience.",
    description: "REJUV 70mg blend for research protocols, independently tested for identity and mass.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-REJUV70-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "66",
    slug: "semaglutide-5mg",
    sku: "SEMA-5",
    name: "SEMAGLUTIDE 5MG",
    category: "peptides",
    categoryLabel: "Peptides",
    image: "/images/products/semaglutide.png",
    price: 90,
    bulkOption: { qty: 10, price: 720, savePercent: 20 },
    purity: "99.7%",
    avgMass: "5.01 mg",
    rating: 4.8,
    reviewCount: 52,
    inStock: true,
    shortDescription: "GLP-1 receptor agonist research peptide, standard concentration.",
    description: "Semaglutide 5mg vial for research protocols. 99.7% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-SEMA5-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "67",
    slug: "semax-10mg",
    sku: "SEMAX-10",
    name: "SEMAX 10MG",
    category: "peptides",
    categoryLabel: "Peptides",
    image: "/images/products/semax.png",
    price: 65,
    bulkOption: { qty: 10, price: 520, savePercent: 20 },
    purity: "99.4%",
    avgMass: "10.03 mg",
    rating: 4.7,
    reviewCount: 20,
    inStock: true,
    shortDescription: "Nootropic heptapeptide research compound, standard concentration.",
    description: "Semax 10mg vial for research protocols. 99.4% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-SEMAX10-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "68",
    slug: "slu-pp-332-5mg",
    sku: "SLUPP-5",
    name: "SLU-PP-332 5MG",
    category: "peptides",
    categoryLabel: "Peptides",
    image: "/images/products/slu-pp-332.png",
    price: 95,
    bulkOption: { qty: 10, price: 760, savePercent: 20 },
    purity: "99.0%",
    avgMass: "5.05 mg",
    rating: 4.5,
    reviewCount: 6,
    inStock: true,
    shortDescription: "Exercise-mimetic research compound, standard concentration.",
    description: "SLU-PP-332 5mg vial for research protocols. 99.0% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-SLUPP5-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "69",
    slug: "snap-8-10mg",
    sku: "SNAP8-10",
    name: "SNAP-8 10MG",
    category: "peptides",
    categoryLabel: "Peptides",
    image: "/images/products/snap-8.png",
    price: 55,
    bulkOption: { qty: 10, price: 440, savePercent: 20 },
    purity: "99.2%",
    avgMass: "10.04 mg",
    rating: 4.6,
    reviewCount: 11,
    inStock: true,
    shortDescription: "Anti-wrinkle octapeptide research compound, standard concentration.",
    description: "SNAP-8 10mg vial for research protocols. 99.2% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-SNAP810-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "70",
    slug: "ss-31-10mg",
    sku: "SS31-10",
    name: "SS-31 10MG",
    category: "peptides",
    categoryLabel: "Peptides",
    image: "/images/products/ss-31.png",
    price: 95,
    bulkOption: { qty: 10, price: 760, savePercent: 20 },
    purity: "99.5%",
    avgMass: "10.02 mg",
    rating: 4.7,
    reviewCount: 15,
    inStock: true,
    shortDescription: "Mitochondria-targeted research peptide, standard concentration.",
    description: "SS-31 10mg vial for research protocols. 99.5% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-SS3110-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "71",
    slug: "tb-500-5mg",
    sku: "TB500-5",
    name: "TB-500 5MG",
    category: "peptides",
    categoryLabel: "Peptides",
    image: "/images/products/tb-500.png",
    price: 65,
    bulkOption: { qty: 10, price: 520, savePercent: 20 },
    purity: "99.6%",
    avgMass: "5.03 mg",
    rating: 4.8,
    reviewCount: 47,
    inStock: true,
    shortDescription: "Thymosin Beta-4 fragment research peptide, standard concentration.",
    description: "TB-500 5mg vial for research protocols. 99.6% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-TB5005-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "72",
    slug: "thymalin-10mg",
    sku: "THYM-10",
    name: "THYMALIN 10MG",
    category: "peptides",
    categoryLabel: "Peptides",
    image: "/images/products/thymalin.png",
    price: 65,
    bulkOption: { qty: 10, price: 520, savePercent: 20 },
    purity: "99.3%",
    avgMass: "10.04 mg",
    rating: 4.6,
    reviewCount: 10,
    inStock: true,
    shortDescription: "Thymic peptide research compound, standard concentration.",
    description: "Thymalin 10mg vial for research protocols. 99.3% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-THYM10-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "73",
    slug: "tirzepatide-10mg",
    sku: "TIRZ-10",
    name: "TIRZEPATIDE 10MG",
    category: "peptides",
    categoryLabel: "Peptides",
    image: "/images/products/tirzepatide.png",
    price: 95,
    bulkOption: { qty: 10, price: 760, savePercent: 20 },
    purity: "99.7%",
    avgMass: "10.01 mg",
    rating: 4.9,
    reviewCount: 61,
    inStock: true,
    shortDescription: "GIP/GLP-1 dual-agonist research peptide, standard concentration.",
    description: "Tirzepatide 10mg vial for research protocols. 99.7% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-TIRZ10-08", date: "2026-08-23", status: "PASS" },
  },
  {
    id: "74",
    slug: "vip-10mg",
    sku: "VIP-10",
    name: "VIP 10MG",
    category: "peptides",
    categoryLabel: "Peptides",
    image: "/images/products/vip.png",
    price: 70,
    bulkOption: { qty: 10, price: 560, savePercent: 20 },
    purity: "99.2%",
    avgMass: "10.03 mg",
    rating: 4.6,
    reviewCount: 9,
    inStock: true,
    shortDescription: "Vasoactive intestinal peptide research compound, standard concentration.",
    description: "VIP 10mg vial for research protocols. 99.2% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-VIP10-08", date: "2026-08-23", status: "PASS" },
  },
];

export function getProducts() {
  return products;
}

export function getFeaturedProducts() {
  return products.filter((p) => ["bpc-157-10mg", "retatrutide-10mg", "ghk-cu-50mg", "mots-c-10mg"].includes(p.slug));
}

export function getProductBySlug(slug: string) {
  return products.find((p) => p.slug === slug);
}

export function getRelatedProducts(slug: string, limit = 4) {
  const current = getProductBySlug(slug);
  if (!current) return [];
  return products.filter((p) => p.slug !== slug && p.category === current.category).slice(0, limit);
}

export const categories: { value: Product["category"] | "all"; label: string }[] = [
  { value: "all", label: "All Products" },
  { value: "growth-hormone", label: "Growth Hormone" },
  { value: "peptides", label: "Peptides" },
  { value: "ancillaries", label: "Ancillaries" },
];
