import { Product } from "./types";

/**
 * Mock catalog shaped to mirror the WooCommerce REST/Store API product
 * schema (id, slug, sku, price, stock_status, categories, meta_data for
 * purity/mass/batch). Swap `getProducts` / `getProductBySlug` for real
 * fetches against the WooCommerce API once the WordPress site is live —
 * see lib/woocommerce.ts.
 */
export const products: Product[] = [
  {
    id: "1",
    slug: "bpc-157-5mg",
    sku: "BPC-5",
    name: "BPC-157 5MG",
    category: "peptides",
    categoryLabel: "Peptides",
    price: 40,
    bulkOption: { qty: 10, price: 320, savePercent: 20 },
    purity: "99.88%",
    avgMass: "5.84 mg",
    rating: 4.9,
    reviewCount: 156,
    inStock: true,
    shortDescription: "A well-studied research peptide used in tissue-repair protocols.",
    description:
      "BPC-157 5mg, lyophilized and independently verified for identity and purity. Supplied for laboratory research use only.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-BPC5-08", date: "2026-08-12", status: "PASS" },
  },
  {
    id: "2",
    slug: "bpc-157-10mg",
    sku: "BPC-10",
    name: "BPC-157 10MG",
    category: "peptides",
    categoryLabel: "Peptides",
    image: "/images/products/bpc-157.jpg",
    price: 70,
    bulkOption: { qty: 10, price: 560, savePercent: 20 },
    purity: "98.51%",
    avgMass: "11.22 mg",
    rating: 4.8,
    reviewCount: 89,
    inStock: true,
    shortDescription: "Higher-concentration BPC-157 for extended research protocols.",
    description:
      "BPC-157 10mg, lyophilized and independently verified for identity and purity. Supplied for laboratory research use only.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-BPC10-08", date: "2026-08-09", status: "PASS" },
  },
  {
    id: "3",
    slug: "tirzepatide-10mg",
    sku: "TIRZ-10",
    name: "TIRZEPATIDE 10MG",
    category: "peptides",
    categoryLabel: "Peptides",
    price: 60,
    bulkOption: { qty: 10, price: 480, savePercent: 20 },
    purity: "99.51%",
    avgMass: "10.62 mg",
    rating: 4.7,
    reviewCount: 56,
    inStock: true,
    shortDescription: "Dual-agonist research peptide, standard concentration.",
    description:
      "Tirzepatide 10mg vial for research protocols. 99.51% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-TIRZ10-07", date: "2026-07-28", status: "PASS" },
  },
  {
    id: "4",
    slug: "tirzepatide-30mg",
    sku: "TIRZ-30",
    name: "TIRZEPATIDE 30MG",
    category: "peptides",
    categoryLabel: "Peptides",
    price: 150,
    bulkOption: { qty: 10, price: 1200, savePercent: 20 },
    purity: "99.81%",
    avgMass: "35.30 mg",
    rating: 4.8,
    reviewCount: 38,
    inStock: true,
    shortDescription: "High-concentration Tirzepatide vial for extended research protocols.",
    description:
      "High-concentration Tirzepatide 30mg vial for extended research protocols. 99.81% purity verified by independent testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with genuine bacteriostatic water intended for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-TIRZ30-07", date: "2026-07-28", status: "PASS" },
  },
  {
    id: "5",
    slug: "semaglutide-5mg",
    sku: "SEMA-5",
    name: "SEMAGLUTIDE 5MG",
    category: "peptides",
    categoryLabel: "Peptides",
    price: 50,
    bulkOption: { qty: 10, price: 400, savePercent: 20 },
    purity: "99.39%",
    avgMass: "5.03 mg",
    rating: 4.6,
    reviewCount: 48,
    inStock: true,
    shortDescription: "GLP-1 research peptide, standard concentration.",
    description:
      "Semaglutide 5mg vial for research protocols. 99.39% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-SEMA5-08", date: "2026-08-05", status: "PASS" },
  },
  {
    id: "6",
    slug: "semaglutide-10mg",
    sku: "SEMA-10",
    name: "SEMAGLUTIDE 10MG",
    category: "peptides",
    categoryLabel: "Peptides",
    price: 80,
    bulkOption: { qty: 10, price: 640, savePercent: 20 },
    purity: "99.64%",
    avgMass: "10.85 mg",
    rating: 4.8,
    reviewCount: 82,
    inStock: true,
    shortDescription: "GLP-1 research peptide, higher concentration.",
    description:
      "Semaglutide 10mg vial for research protocols. 99.64% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-SEMA10-08", date: "2026-08-05", status: "PASS" },
  },
  {
    id: "7",
    slug: "retatrutide-10mg",
    sku: "RETA-10",
    name: "RETATRUTIDE 10MG",
    category: "peptides",
    categoryLabel: "Peptides",
    image: "/images/products/retatrutide.jpg",
    price: 90,
    bulkOption: { qty: 10, price: 720, savePercent: 20 },
    purity: "99.69%",
    avgMass: "10.99 mg",
    rating: 4.7,
    reviewCount: 45,
    inStock: true,
    shortDescription: "Tri-agonist research peptide, standard concentration.",
    description:
      "Retatrutide 10mg vial for research protocols. 99.69% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-RETA10-07", date: "2026-07-30", status: "PASS" },
  },
  {
    id: "8",
    slug: "tb-500-5mg",
    sku: "TB-5",
    name: "TB-500 5MG",
    category: "peptides",
    categoryLabel: "Peptides",
    price: 40,
    bulkOption: { qty: 10, price: 320, savePercent: 20 },
    purity: "99.74%",
    avgMass: "5.87 mg",
    rating: 4.7,
    reviewCount: 73,
    inStock: true,
    shortDescription: "Recovery-focused research peptide, standard concentration.",
    description:
      "TB-500 5mg vial for research protocols. 99.74% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-TB5-07", date: "2026-07-20", status: "PASS" },
  },
  {
    id: "9",
    slug: "bpc-157-tb-500-blend-6mg-6mg",
    sku: "BLEND-6-6",
    name: "BPC-157 / TB-500 Healing Blend 6MG/6MG",
    category: "peptides",
    categoryLabel: "Peptides",
    price: 70,
    bulkOption: { qty: 10, price: 560, savePercent: 20 },
    avgMass: "11.74 mg",
    rating: 4.8,
    reviewCount: 67,
    inStock: true,
    shortDescription: "Combined blend of two commonly co-researched repair peptides.",
    description:
      "A pre-combined BPC-157 / TB-500 blend for research convenience. Independently tested for identity and mass.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-BLEND-08", date: "2026-08-08", status: "PASS" },
  },
  {
    id: "10",
    slug: "tesamorelin-10mg",
    sku: "TESA-10",
    name: "TESAMORELIN 10MG",
    category: "peptides",
    categoryLabel: "Peptides",
    price: 90,
    bulkOption: { qty: 10, price: 720, savePercent: 20 },
    purity: "99.86%",
    avgMass: "11.83 mg",
    rating: 4.6,
    reviewCount: 29,
    inStock: true,
    shortDescription: "GHRH-analog research peptide, standard concentration.",
    description:
      "Tesamorelin 10mg vial for research protocols. 99.86% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-TESA10-07", date: "2026-07-18", status: "PASS" },
  },
  {
    id: "11",
    slug: "cagrilintide-10mg",
    sku: "CAGRI-10",
    name: "CAGRILINTIDE 10MG",
    category: "peptides",
    categoryLabel: "Peptides",
    price: 100,
    bulkOption: { qty: 10, price: 800, savePercent: 20 },
    purity: "99.66%",
    avgMass: "10.28 mg",
    rating: 4.5,
    reviewCount: 18,
    inStock: true,
    shortDescription: "Amylin-analog research peptide, standard concentration.",
    description:
      "Cagrilintide 10mg vial for research protocols. 99.66% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-CAGRI10-08", date: "2026-08-02", status: "PASS" },
  },
  {
    id: "12",
    slug: "hcg-7000iu",
    sku: "HCG-7K",
    name: "HCG 7,000IU",
    category: "peptides",
    categoryLabel: "Peptides",
    price: 40,
    bulkOption: { qty: 10, price: 320, savePercent: 20 },
    avgMass: "8,014 mg",
    rating: 4.5,
    reviewCount: 31,
    inStock: true,
    shortDescription: "Standard-dose HCG vial for research protocols.",
    description: "HCG 7,000IU vial for research protocols, independently verified for mass.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-HCG7-06", date: "2026-06-30", status: "PASS" },
  },
  {
    id: "13",
    slug: "growth-hormone-kit-280iu",
    sku: "GH-280",
    name: "Growth Hormone — Batch ALT38 280IU Kit",
    category: "growth-hormone",
    categoryLabel: "Growth Hormone",
    price: 280,
    purity: "93.84%",
    avgMass: "28.15 ius",
    rating: 4.9,
    reviewCount: 127,
    inStock: true,
    shortDescription: "Full research kit, independently verified batch.",
    description:
      "Growth hormone research kit, batch ALT38. Independently tested for purity and mass, supplied for laboratory research only.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    batch: { code: "ALT38", date: "2026-07-15", status: "PASS" },
  },
  {
    id: "14",
    slug: "growth-hormone-kit-420iu",
    sku: "GH-420",
    name: "Growth Hormone — Batch ALT39 420IU Kit",
    category: "growth-hormone",
    categoryLabel: "Growth Hormone",
    price: 400,
    purity: "96.57%",
    avgMass: "42.62 ius",
    rating: 4.9,
    reviewCount: 94,
    inStock: true,
    shortDescription: "Full research kit, independently verified batch.",
    description:
      "Growth hormone research kit, batch ALT39. Independently tested for purity and mass, supplied for laboratory research only.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    batch: { code: "ALT39", date: "2026-06-22", status: "PASS" },
  },
  {
    id: "15",
    slug: "bacteriostatic-water",
    sku: "BAC-H2O",
    name: "Bacteriostatic Water",
    category: "ancillaries",
    categoryLabel: "Ancillaries",
    price: 25,
    rating: 4.9,
    reviewCount: 211,
    inStock: true,
    shortDescription: "Pharmaceutical-grade reconstitution water.",
    description: "Pharmaceutical-grade bacteriostatic water for reconstituting lyophilized research compounds.",
    storage: "Store at room temperature, away from direct light.",
  },
  {
    id: "16",
    slug: "nad-350mg",
    sku: "NAD-350",
    name: "NAD+ 350MG",
    category: "ancillaries",
    categoryLabel: "Peptides, Ancillaries",
    price: 55,
    bulkOption: { qty: 10, price: 440, savePercent: 20 },
    purity: "99.2%",
    avgMass: "352 mg",
    rating: 4.6,
    reviewCount: 19,
    inStock: true,
    shortDescription: "Coenzyme research compound, standard concentration.",
    description: "NAD+ 350mg vial for research protocols. 99.2% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-NAD350-08", date: "2026-08-14", status: "PASS" },
  },
  {
    id: "17",
    slug: "ghk-cu-50mg",
    sku: "GHK-50",
    name: "GHK-CU 50MG",
    category: "ancillaries",
    categoryLabel: "Peptides, Ancillaries",
    image: "/images/products/ghk-cu.jpg",
    price: 65,
    bulkOption: { qty: 10, price: 520, savePercent: 20 },
    purity: "99.4%",
    avgMass: "50.1 mg",
    rating: 4.7,
    reviewCount: 24,
    inStock: true,
    shortDescription: "Copper-peptide research compound, standard concentration.",
    description: "GHK-Cu 50mg vial for research protocols. 99.4% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-GHK50-08", date: "2026-08-16", status: "PASS" },
  },
  {
    id: "18",
    slug: "mots-c-10mg",
    sku: "MOTS-10",
    name: "MOTS-C 10MG",
    category: "ancillaries",
    categoryLabel: "Peptides, Ancillaries",
    image: "/images/products/mots-c.jpg",
    price: 75,
    bulkOption: { qty: 10, price: 600, savePercent: 20 },
    purity: "99.5%",
    avgMass: "10.15 mg",
    rating: 4.8,
    reviewCount: 17,
    inStock: true,
    shortDescription: "Mitochondrial-derived peptide, standard concentration.",
    description: "MOTS-c 10mg vial for research protocols. 99.5% purity verified by independent third-party testing.",
    storage: "Store lyophilized vials at 2–8°C. After reconstitution, use within 30 days and refrigerate.",
    reconstitution: "Reconstitute with bacteriostatic or sterile water appropriate for laboratory use.",
    badges: ["Save 20%"],
    batch: { code: "ALT-MOTS10-08", date: "2026-08-17", status: "PASS" },
  },
];

export function getProducts() {
  return products;
}

export function getFeaturedProducts() {
  return products.filter((p) => ["bpc-157-10mg", "retatrutide-10mg", "ghk-cu-50mg", "mots-c-10mg"].includes(p.slug));
}

export function getProductBySlug(slug: string) {
  return products.find((p) => p.slug === slug);
}

export function getRelatedProducts(slug: string, limit = 4) {
  const current = getProductBySlug(slug);
  if (!current) return [];
  return products.filter((p) => p.slug !== slug && p.category === current.category).slice(0, limit);
}

export const categories: { value: Product["category"] | "all"; label: string }[] = [
  { value: "all", label: "All Products" },
  { value: "growth-hormone", label: "Growth Hormone" },
  { value: "peptides", label: "Peptides" },
  { value: "ancillaries", label: "Ancillaries" },
];
